# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Fuseraft.Anchor
PackageVersion: 0.3.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchor.exe
  PortableCommandAlias: anchor
ReleaseDate: 2026-10-04
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/fuseraft/anchor/releases/download/v0.3.1/anchor-0.3.1-win-x64.zip
  InstallerSha256: 4691CC96B3359EE32D82779A6B56AC35BE4D843D4D419A0AF73B1F082688E939
ManifestType: installer
ManifestVersion: 1.12.0
